name: C_C++_CI

on:
  workflow_call:
    inputs:
      dependencies:
        required: true
        type: string
    secrets:
      CPP_GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_version: [3.16.3]
        gcc_version: [9]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      # - name: Get dependencies
      #   env:
      #     cmake_version: ${{ matrix.cmake_version }}
      #     gcc_version: ${{ matrix.gcc_version }}
      #   uses: NWChemEx-Project/.github/actions/get_dependencies@master
      #   with:
      #     dependencies: ${{inputs.dependencies}}
      - name: For NWChemEx-Project
        if: github.event.repository.name == 'NWChemEx'
        run: echo 'inside NWChemEx'
      # - name: Build and test
      #   env:
      #     cmake_version: ${{ matrix.cmake_version }}
      #     gcc_version: ${{ matrix.gcc_version }}
      #   uses: NWChemEx-Project/.github/actions/build_and_test@master
      #   with: 
      #     CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml