name: Build and Deploy Documentation
on:
  workflow_call:
    inputs:
      reponame_cxx_api:
        required: true
        type: string
      dependencies:
        required: true
        type: string
jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    env:
      cmake_version: 3.16.3
      arch: Linux-x86_64
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get dependencies
        uses: NWChemEx-Project/.github/actions/get_dependencies@demo-0.0.2
        with:
          dependencies: ${{inputs.dependencies}}
      - name: Build documentation
        uses: NWChemEx-Project/.github/actions/build_docs@demo-0.0.2
        with:
          repoName: ${{inputs.reponame_cxx_api}}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./docs/build/html
