

name: Build and Deploy Documentation
on:
  workflow_call:
    inputs:
      dependencies:
        required: true
        type: string
jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    env:
      cmake_version: 3.16.3
      arch: Linux-x86_64
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: cache-libint
          if: contains(${{inputs.dependencies}}, 'libint')
          id: cache
          uses: actions/cache@v2
          with:
            path: |
              libint-2.6.0/
              install/
            key: libint-gcc${{ matrix.gcc_version }}
