name: Test Documentation with Docker Image
on:
  workflow_call:
    inputs:
      target:
        type: string
      dependencies:
        required: true
        type: string
      skip_doxygen:
        type: boolean
    secrets:
      CONTAINER_REPO_TOKEN:
        description: 'Token passed from the caller workflow to pull the docker image'
        required: true
      
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nwchemex-project/build_doc:v1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REPO_TOKEN }}
    strategy:
      matrix:
        cmake_version: [3.17.0]
    steps:
    - name: Obtain Source
      uses: actions/checkout@v2
    - name: Build documentation
      env:
        cmake_version: ${{ matrix.cmake_version }}
      uses: NWChemEx-Project/.github/actions/image-build_docs@master
      with:
        target: ${{inputs.target}}
        skip_doxygen: ${{inputs.skip_doxygen}}
